include:
    - docker-compose-keycloak-postgres.yml

services:
    postgres_db:
        image: postgres:15
        container_name: postgres_srealizacao

        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: srealizacao
        ports:
            - "5432:5432"
        volumes:
            - ../DOCKER/BANCOS/postgres-data:/var/lib/postgresql/data
        networks:
            - srealizacao-net

    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - ENVIRONMENT=homolog #sobrescrever no Dockerfile
        container_name: srealizacao-backend
        ports:
            - "8080:8080"
        networks:
            - srealizacao-net
        depends_on:
            - postgres_db
        healthcheck:
            test: ["CMD", "sh", "-C", "curl -f http://localhost:$8080/actuator/helth | grep -i UP || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 10s

networks:
    srealizacao-net:
        driver: bridge

